# Generated by Django 3.1.1 on 2020-09-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('reg_name', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('role', models.IntegerField(default=1)),
                ('city', models.CharField(default='abc', max_length=50)),
                ('state', models.CharField(default='abc', max_length=50)),
                ('country', models.CharField(default='abc', max_length=50)),
                ('phone', models.CharField(default='9999999999', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
