# Generated by Django 3.1.1 on 2020-09-25 09:36

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=1000)),
                ('nct_no', models.CharField(max_length=50, unique=True)),
                ('drug_image_path', models.ImageField(upload_to=dashboard.models.saveimage)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('other_medications', models.CharField(max_length=2000)),
                ('comorbid_conditions', models.CharField(max_length=2000)),
                ('blood_pressure_req', models.IntegerField()),
                ('posology', models.CharField(max_length=200)),
                ('efficacy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drug_category', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
    ]
