# Generated by Django 3.1.1 on 2020-09-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=2000)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('other_medications', models.CharField(max_length=2000)),
                ('comorbid_conditions', models.CharField(max_length=2000)),
                ('blood_pressure_req', models.IntegerField()),
                ('posology', models.CharField(max_length=100)),
                ('drug_category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('contact_info', models.CharField(max_length=13)),
                ('comorbid_conditions', models.CharField(max_length=2000)),
                ('hereditary_diseases', models.CharField(max_length=2000)),
                ('allergies', models.CharField(max_length=2000)),
                ('entry_date', models.DateField()),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=2000)),
                ('severity', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('bp_sys', models.IntegerField()),
                ('bp_dys', models.IntegerField()),
                ('prescribed_drug', models.CharField(max_length=1000)),
                ('prescribed_treatment', models.CharField(max_length=1000)),
                ('precautions', models.CharField(max_length=2000)),
                ('past_medications', models.CharField(max_length=1000)),
                ('diagnosis_date', models.DateField()),
                ('admit_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patients')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
    ]
