# Generated by Django 3.1.1 on 2020-09-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='p_id',
            new_name='p',
        ),
    ]
