# Generated by Django 3.1.1 on 2020-09-25 16:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200925_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='drug_image_path',
            field=models.ImageField(default='default.jpg', upload_to=dashboard.models.saveimage),
        ),
    ]
