# Generated by Django 3.1.1 on 2020-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_diagnosis_hospitaldrugs_patients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='drugs',
            options={'verbose_name_plural': 'Drugs'},
        ),
        migrations.AlterModelOptions(
            name='hospitaldrugs',
            options={'verbose_name_plural': 'HospitalDrugs'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='drugs',
            name='blood_pressure_req',
            field=models.CharField(max_length=100),
        ),
    ]
